### ISSUE TITLE
Atempt to invoke virtual method 'void android.app.Activity.startIntentSenderForResult()' on a null object reference

### ISSUE THREAD

**Issue by gel-prog** [StasDoskalenko/react-native-google-fit#199]
Every time I freshly install the app, given the app is in the background but the permissions screen is visible I get the following error:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.startIntentSenderForResult(android.content.IntentSender, int, android.content.Intent, int, int, int)' on a null object reference
    at com.google.android.gms.common.ConnectionResult.startResolutionForResult
    at com.reactnative.googlefit.GoogleFitManager$1.onConnectionFailed(GoogleFitManager.java:172)
    at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionFailure
    at com.google.android.gms.common.api.internal.zzav.zzc
    at com.google.android.gms.common.api.internal.zzaj.zze
    at com.google.android.gms.common.api.internal.zzaj.zza
    at com.google.android.gms.common.api.internal.zzaj.zza
    at com.google.android.gms.common.api.internal.zzar.zzaq
    at com.google.android.gms.common.api.internal.zzbe.zzc
    at com.google.android.gms.common.api.internal.zzbf.handleMessage
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6718)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Using version react-native-google-fit 0.12.2.

**Comment by gel-prog** [comment]
This is probably more related to https://github.com/facebook/react-native/issues/18345.

**Comment by gel-prog** [comment]
This is probably more related to https://github.com/facebook/react-native/issues/18345.
