### ISSUE TITLE
NullPointerException onConnectionFailed

### ISSUE THREAD

**Issue by mabc21** [StasDoskalenko/react-native-google-fit#225]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.app.Activity.startIntentSenderForResult(android.content.IntentSender, int, android.content.Intent, int, int, int)' on a null object reference

com.google.android.gms.common.ConnectionResult.startResolutionForResult (com.google.android.gms:play-services-basement@@17.1.1:17)
com.reactnative.googlefit.GoogleFitManager$1.onConnectionFailed (GoogleFitManager.java:172)
com.google.android.gms.common.internal.GmsClientEventManager.onConnectionFailure (com.google.android.gms:play-services-base@@17.1.0:61) 

The crash seems to happen the first time around, but when you access again, no exception. Even though isauthorized is true.  Thoughts?

**Comment by davetaylor** [comment]
Hi @mabc21 ! I am also seeing this in my crash logs. Is this still occurring for you, and if so what versions are you having the problems with? Thanks!

**Comment by maidinhkhoa92** [comment]
I got this crash with 0.18.3 
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.startIntentSenderForResult(android.content.IntentSender, int, android.content.Intent, int, int, int)' on a null object reference
       at com.google.android.gms.common.ConnectionResult.startResolutionForResult(com.google.android.gms:play-services-basement@@18.0.0:2)
       at com.reactnative.googlefit.GoogleFitManager$1.onConnectionFailed(GoogleFitManager.java:189)
       at com.google.android.gms.common.internal.zak.zac(com.google.android.gms:play-services-base@@18.0.1:8)
       at com.google.android.gms.common.api.internal.zabe.zaa(com.google.android.gms:play-services-base@@18.0.1:3)
       at com.google.android.gms.common.api.internal.zaaw.zaD(com.google.android.gms:play-services-base@@18.0.1:4)
       at com.google.android.gms.common.api.internal.zaaw.zar(com.google.android.gms:play-services-base@@18.0.1:16)
       at com.google.android.gms.common.api.internal.zaaq.zaa(com.google.android.gms:play-services-base@@18.0.1:1)
       at com.google.android.gms.common.api.internal.zabg.zab(com.google.android.gms:play-services-base@@18.0.1:4)
       at com.google.android.gms.common.api.internal.zabh.handleMessage(com.google.android.gms:play-services-base@@18.0.1:4)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7886)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:970)`

**Comment by Nolascoin** [comment]
I got it too with 0.18.2

`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.app.Activity.startIntentSenderForResult(android.content.IntentSender, int, android.content.Intent, int, int, int)' on a null object reference`

**Comment by ClementAGIL** [comment]
Hello, Any news on this issue ? 
I got it too with 0.18.2 and nothing seems to have been done about it even in the latest version (0.19.1).

```
NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.startIntentSenderForResult(android.content.IntentSender, int, android.content.Intent, int, int, int)' on a null object reference
2    at com.google.android.gms.common.ConnectionResult.startResolutionForResult(com.google.android.gms:play-services-basement@@17.5.0:17)
3    at com.reactnative.googlefit.GoogleFitManager$1.onConnectionFailed(GoogleFitManager.java:189)
4    at com.google.android.gms.common.internal.zah.zaa(com.google.android.gms:play-services-base@@17.5.0:58)
5    at com.google.android.gms.common.api.internal.zaar.zaa(com.google.android.gms:play-services-base@@17.5.0:302)
6    at com.google.android.gms.common.api.internal.zaaf.zab(com.google.android.gms:play-services-base@@17.5.0:166)
```

**Comment by wojtas1413** [comment]
@Nolascoin have you managed to solve the issue?

**Comment by Nolascoin** [comment]
> @Nolascoin have you managed to solve the issue?

My PR https://github.com/Nolascoin/react-native-google-fit/commit/44e31a430544bb486282a4608c7b54065c2a432c circumvents the issue by not crashing, but does not fix the problem.
